# This configuration file defines the mapping of local data into BBMRI-cohorts categories

# Specify biobank id and collection id: (from Directory)
biobank_id: bbmri-eric:ID:IT_1111111111
collection_id: bbmri-eric:ID:IT_1111111111:collection:eee1112e21e2
collection_alias: KDN

# needed: sex/age/material_type/diagnosis(icd-10)

# Define the names of each field
field_mappings:

  PATIENT_ID: ID Patient
  SAMPLE_ID: ID Sample
  SEX: Sex
  DONOR_AGE: Donor age
  DIAGNOSIS: Biobanca_ICD code
  MATERIAL_TYPE: Sample Type
  
  
  
# Define the names of each value 
value_mappings:
  SEX: # (https://directory-backend.molgenis.net/menu/codelists/dataexplorer?entity=eu_bbmri_eric_sex_types)
    MALE: M
    FEMALE: F
    UNDIFFERENTIAL: undifferentiated
    UNKNOWN: unknown

  MATERIAL_TYPE: #(https://directory-backend.molgenis.net/menu/codelists/dataexplorer?entity=eu_bbmri_eric_material_types#)
    BUFFY_COAT: Buffy Coat
    CDNA: CDNA
    CELL_LINES: Cells
    DNA: DNA
    FECES: Feces
    MICRO_RNA: MicroRNA
    NASAL_SWAB: Nasal Swab
    NAV: NAV
    OTHER: LIQUOR
    PATHOGEN: Pathogen
    PERIPHERAL_BLOOD_CELLS: Blood Cells
    PLASMA: PLASMA
    RNA: RNA
    SALIVA: Saliva
    SERUM: SERUM
    THROAT_SWAB: Throat Swab
    TISSUE_FROZEN: Tissue Frozen
    TISSUE_PARAFFIN_EMBEDDED: Tissue FFPE
    TISSUE_STAINED: Tissue Stained
    URINE: Urine
    WHOLE_BLOOD: Blood



