# This configuration file defines the mapping of local data into BBMRI-cohorts categories

# Specify biobank id and collection id: (taken from Directory)
biobank_id: bbmri-eric:ID:IT_1111111111
collection_id: bbmri-eric:ID:IT_1111111111:collection:eee1112e21e2

# needed: sex/age/material_type/diagnosis

# Define the names of each field
field_mappings:

  PATIENT_ID: ID Patient
  SAMPLE_ID: ID Sample
  SEX: Sex
  DONOR_AGE: Donor age
  DIAGNOSIS: Biobanca_ICD code
  MATERIAL_TYPE: Sample Type
  
  
  
# Define the names of each value 
value_mappings:
  SEX:
    MALE: M
    FEMALE: F
    UNDIFFERENTIAL: undifferentiated
    UNKNOWN: unknown

  MATERIAL_TYPE:
    TISSUE_PARAFFIN_EMBEDDED: FFPE
    TISSUE_FROZEN:
      - SNAP FROZEN
      - FROZEN
      - OCT
    BLOOD: BLOOD
    FAECES: FECIS
    BUFFY_COAT: BUFFY COAT
    RNA: RNA
    DNA:
    - DNA
    - GDNA
    SALIVA: SALIVA
    URINE: URINE
    CELL_LINE: CELLS
    OTHER: SN
    SERUM: SERUM
    PLASMA: PLASMA
    LIQUOR: LIQUOR
    WHOLE_BLOOD: WHOLE BLOOD
    PATHOGEN:
    THROAT_SWAB:
    CDNA:
    NASAL_SWAB:
    TISSUE_STAINED:
    PERIPHERAL_BLOOD_CELLS:
    MICRO_RNA:



